# Generated by Django 3.1.4 on 2020-12-23 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_category_name', models.CharField(max_length=100)),
                ('blog_category_value', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'BlogCategory',
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_category_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'JobCategory',
            },
        ),
        migrations.CreateModel(
            name='JobSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('job_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_webapp.jobcategory')),
            ],
            options={
                'verbose_name_plural': 'JobSubCategory',
            },
        ),
        migrations.CreateModel(
            name='PostAJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Freelance', 'Freelancer')], max_length=50, null=True)),
                ('other', models.CharField(blank=True, max_length=150, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('age_limit', models.IntegerField(blank=True, null=True)),
                ('uniform', models.CharField(blank=True, max_length=150)),
                ('pay_type', models.CharField(blank=True, choices=[('Fixed Pay', 'Fixed Pay'), ('Hourly Pay', 'Hourly Pay'), ('Weekly Pay', 'Weekly Pay'), ('Daily Pay', 'Daily Pay'), ('Monthly Pay', 'Monthly Pay')], max_length=50, null=True)),
                ('pay_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('no_of_openning', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('location_instructor', models.CharField(blank=True, max_length=150, null=True)),
                ('parking', models.CharField(blank=True, max_length=50, null=True)),
                ('break_time', models.CharField(blank=True, max_length=50, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('preference', models.CharField(blank=True, max_length=50, null=True)),
                ('appearance_preference', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('For Both', 'For Both')], max_length=10, null=True)),
                ('view_applicants', models.CharField(blank=True, max_length=50, null=True)),
                ('job_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_webapp.jobcategory')),
                ('job_sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_webapp.jobsubcategory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PostAJob',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_feature_image', models.ImageField(blank=True, null=True, upload_to='media/images/')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('paragraph_content', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=100, null=True)),
                ('author_name', models.CharField(blank=True, max_length=50, null=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('blog_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_webapp.blogcategory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Blog',
            },
        ),
    ]
