# Generated by Django 3.1.4 on 2020-12-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_webapp', '0002_auto_20201224_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='upload_feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
