# Generated by Django 3.1.4 on 2020-12-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_webapp', '0003_auto_20201224_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='job_category_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
