# Generated by Django 3.1.4 on 2020-12-25 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_webapp', '0004_jobcategory_job_category_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postajob',
            old_name='other',
            new_name='job_title',
        ),
    ]
