# Generated by Django 3.1.4 on 2020-12-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='media/images/')),
                ('account_type', models.CharField(choices=[('S', 'Super Admin'), ('A', 'Admin'), ('U', 'User')], default='U', max_length=1)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('facebook_id', models.CharField(blank=True, max_length=100, null=True)),
                ('google_id', models.CharField(blank=True, max_length=100, null=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('is_verified_phone', models.BooleanField(default=False)),
                ('otp_created', models.DateTimeField(blank=True, null=True)),
                ('countrycode', models.CharField(blank=True, max_length=9, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
